#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

use Gogol\VpsManagerCLI\Command\Backup\BackupPerformCommand;
use Gogol\VpsManagerCLI\Command\Backup\BackupSetupCommand;
use Gogol\VpsManagerCLI\Command\Backup\BackupTestMailServer;
use Gogol\VpsManagerCLI\Command\Backup\BackupTestRemoteServer;
use Gogol\VpsManagerCLI\Command\Chroot\ChrootCreateCommand;
use Gogol\VpsManagerCLI\Command\Chroot\ChrootRemoveCommand;
use Gogol\VpsManagerCLI\Command\Chroot\ChrootUpdateCommand;
use Gogol\VpsManagerCLI\Command\Hosting\HostingCreateCommand;
use Gogol\VpsManagerCLI\Command\Hosting\HostingRemoveCommand;
use Gogol\VpsManagerCLI\Command\InstallManagerCommand;
use Gogol\VpsManagerCLI\Command\Laravel\LaravelOctaneCommand;
use Gogol\VpsManagerCLI\Command\Laravel\LaravelQueueCommand;
use Gogol\VpsManagerCLI\Command\Mysql\MysqlCreateCommand;
use Gogol\VpsManagerCLI\Command\Mysql\MysqlRemoveCommand;
use Gogol\VpsManagerCLI\Command\Mysql\MysqlResetPasswordCommand;
use Gogol\VpsManagerCLI\Command\Monitor\MonitorAccessLogCommand;
use Gogol\VpsManagerCLI\Command\Monitor\MonitorListCommand;
use Gogol\VpsManagerCLI\Command\Monitor\MonitorRemoveIpCommand;
use Gogol\VpsManagerCLI\Command\Monitor\MonitorReportCommand;
use Gogol\VpsManagerCLI\Command\Monitor\MonitorScannersCommand;
use Gogol\VpsManagerCLI\Command\SSLCreateCommand;
use Symfony\Component\Console\Application;

$application = new Application('VPS Manager');

$application->addCommand(new InstallManagerCommand());
$application->addCommand(new HostingCreateCommand());
$application->addCommand(new HostingRemoveCommand());
$application->addCommand(new SSLCreateCommand());
$application->addCommand(new MonitorScannersCommand());
$application->addCommand(new MonitorListCommand());
$application->addCommand(new MonitorRemoveIpCommand());
$application->addCommand(new MonitorAccessLogCommand());
$application->addCommand(new MonitorReportCommand());
$application->addCommand(new BackupSetupCommand());
$application->addCommand(new BackupPerformCommand());
$application->addCommand(new BackupTestRemoteServer());
$application->addCommand(new BackupTestMailServer());
$application->addCommand(new MysqlCreateCommand());
$application->addCommand(new MysqlResetPasswordCommand());
$application->addCommand(new MysqlRemoveCommand());
$application->addCommand(new ChrootCreateCommand());
$application->addCommand(new ChrootUpdateCommand());
$application->addCommand(new ChrootRemoveCommand());
$application->addCommand(new LaravelQueueCommand());
$application->addCommand(new LaravelOctaneCommand());

$application->run();
