#!/usr/bin/env php
<?php
require_once 'vendor/autoload.php';

use Gogol\VpsManager\App\Command\HostingCreateCommand;
use Gogol\VpsManager\App\Command\HostingRemoveCommand;
use Gogol\VpsManager\App\Command\InstallManagerCommand;
use Gogol\VpsManager\App\Command\SSLCreateCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new InstallManagerCommand());
$application->add(new HostingCreateCommand());
$application->add(new HostingRemoveCommand());
$application->add(new SSLCreateCommand());

$application->run();
?>