<?php

namespace Gogol\VpsManagerCLI\Helpers;

use Gogol\VpsManagerCLI\Application;

class Certbot extends Application
{
    /**
     * Get path of the directory with Let's Encrypt certificates.
     *
     * @return string
     */
    public function certPath(): string
    {
        return $this->config('ssl_path') ?: '/etc/letsencrypt/live';
    }

    /**
     * Check if Let's Encrypt certificate already exists.
     *
     * @param  string  $domain
     * @return bool
     */
    public function exists(string $domain): bool
    {
        if (! isValidDomain($domain)) {
            return false;
        }

        return file_exists($this->certPath().'/'.$domain);
    }

    /**
     * Replace (non-www to www) redirect section with https redirect for both www and non-www versions.
     *
     * @param  string  $domain
     * @param  string  $nginx_conf
     * @return string
     */
    private function replaceRedirectSection(string $domain, string $nginx_conf): string
    {
        $redirect_section_def = $redirect_section = $this->nginx()->getSection('Default domain redirect (non www to www)', $nginx_conf);

        if ($redirect_section === false) {
            $this->response()
                ->error('<error>Could not find default redirect section in NGINX configuration '.$this->nginx()->getAvailablePath($domain).'. Please set redirect manually.</error>')
                ->writeln(null, true);

            return $nginx_conf;
        }

        $first_level_domain = $this->toUserFormat($domain);

        $redirect_section = str_replace(
            'server_name '.$first_level_domain.';',
            "listen 80;\n    listen [::]:80;\n\n".'    server_name www.'.$first_level_domain.' '.$first_level_domain.';',
            $redirect_section,
        );

        // Redirect http to https on the same host first. Both the www redirect
        // and the $host redirect generated by older versions are supported
        $redirect_section = str_replace(
            [
                'return 301 $scheme://www.'.$first_level_domain.'$request_uri;',
                'return 301 $scheme://$host$request_uri;',
            ],
            'return 301 https://$host$request_uri;',
            $redirect_section,
        );

        return str_replace($redirect_section_def, $redirect_section, $nginx_conf);
    }

    /**
     * Get nginx ssl certificate directives.
     *
     * @param  string  $cert_name
     * @return string
     */
    private function getSSLPaths(string $cert_name): string
    {
        $path = $this->certPath().'/'.$cert_name;

        return "\n\n".
            '    ssl_certificate '.$path.'/fullchain.pem;'."\n".
            '    ssl_certificate_key '.$path.'/privkey.pem;'."\n".
            '    include /etc/letsencrypt/options-ssl-nginx.conf;'."\n".
            '    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;';
    }

    /**
     * Get nginx https non-www to www redirect.
     *
     * @param  string  $domain
     * @return string
     */
    public function getSSLWWWRedirect(string $domain): string
    {
        $first_level_domain = $this->toUserFormat($domain);

        return "\n\n".
            '    # Non www to www redirect'."\n".
            '    if ($host = \''.$first_level_domain.'\') {'."\n".
            '        return 301 https://www.'.$first_level_domain.'$request_uri;'."\n".
            '    }';
    }

    /**
     * Update default host section with https listeners and certificates.
     *
     * @param  string  $domain
     * @param  string  $cert_name
     * @param  string  $nginx_conf
     * @return string
     */
    private function replaceDefaultHost(string $domain, string $cert_name, string $nginx_conf): string
    {
        $host_section_def = $host_section = $this->nginx()->getSection('Default host configuration', $nginx_conf);

        if ($host_section === false) {
            $this->response()
                ->error(
                    '<error>Could not find default host section in NGINX configuration '.$this->nginx()->getAvailablePath($domain).'. '.
                    'Please set HTTPS listeners and certificates manually.</error>',
                )
                ->writeln(null, true);

            return $nginx_conf;
        }

        $first_level_domain = $this->toUserFormat($domain);

        $proxy = $this->getProxyProtocol();

        $host_section = str_replace('server_name www.'.$first_level_domain.';', 'server_name www.'.$first_level_domain.' '.$first_level_domain.';', $host_section);
        $host_section = str_replace('listen 80;', 'listen 443 ssl http2'.$proxy.';', $host_section);
        $host_section = str_replace('listen [::]:80;', 'listen [::]:443 ssl http2'.$proxy.';'.$this->getSSLPaths($cert_name).$this->getSSLWWWRedirect($domain), $host_section);

        return str_replace($host_section_def, $host_section, $nginx_conf);
    }

    /**
     * Get proxy_protocol listen parameter when nginx is behind a proxy.
     *
     * @return string
     */
    private function getProxyProtocol(): string
    {
        return $this->config('nginx_is_proxied') ? ' proxy_protocol' : '';
    }

    /**
     * Add subdomain redirect to https version.
     *
     * @param  string  $domain
     * @param  string  $nginx_conf
     * @return string
     */
    private function addSubdomainRedirectSection(string $domain, string $nginx_conf): string
    {
        // If redirect already exists
        if ($this->nginx()->getSection('Redirect to https for subdomain '.$domain, $nginx_conf)) {
            return $nginx_conf;
        }

        $stub = $this->getStub('nginx.redirect.conf');
        $stub->addLineBefore('# Redirect to https for subdomain '.$domain);

        $stub->replace('server_name {from-host};', "listen 80;\n    listen [::]:80;\n\n".'    server_name '.$domain.';');
        $stub->replace('return 301 $scheme://{to-host}$request_uri;', 'return 301 https://$server_name$request_uri;');

        return $nginx_conf."\n\n".$stub;
    }

    /**
     * Add subdomain https host section.
     *
     * @param  string  $domain
     * @param  string  $cert_name
     * @param  string  $nginx_conf
     * @return string
     */
    private function addSubdomainSSLSection(string $domain, string $cert_name, string $nginx_conf): string
    {
        // If https host already exists
        if ($this->nginx()->getSection('HTTPS host for subdomain '.$domain, $nginx_conf)) {
            return $nginx_conf;
        }

        $webPath = $this->getWebPath($domain);

        // If /data path does not exist, use default user dir path
        if (! file_exists($webPath)) {
            $webPath = $this->getUserDirPath($domain);
        }

        $proxy = $this->getProxyProtocol();

        $stub = $this->getStub('nginx.template.conf');
        $stub->addLineBefore('# HTTPS host for subdomain '.$domain);
        $stub->replace('{host}', $domain);
        $stub->replace('{path}', $webPath.'/sub/'.$this->getSubdomain($domain).'/public');
        $stub->replace('{error_log_path}', $this->nginx()->getErrorLogPath($domain, ['www_path' => $webPath]));
        $stub->replace('listen 80;', 'listen 443 ssl http2'.$proxy.';');
        $stub->replace('listen [::]:80;', 'listen [::]:443 ssl http2'.$proxy.';'.$this->getSSLPaths($cert_name));

        // Use existing fpm socket name
        preg_match('/php\d([\s\S]*?)\.sock/', $nginx_conf, $matches);

        $socket_name = count($matches) > 0
            ? trim_end($matches[0], '.sock')
            : $this->php()->getSocketName($domain, $this->config('php_version'));

        $stub->replace('{php_sock_name}', $socket_name);

        return $nginx_conf."\n\n".$stub;
    }

    /**
     * Enable self signed certificates in sites-available/default.
     *
     * @return void
     */
    public function enableDefaultSSLCert(): void
    {
        $default_path = $this->nginx()->getAvailablePath('default');

        $default = @file_get_contents($default_path) ?: '';

        // Uncomment self signed certificates
        $default = str_replace('# listen 443 ssl default_server;', 'listen 443 ssl default_server;', $default);
        $default = str_replace('# listen [::]:443 ssl default_server;', 'listen [::]:443 ssl default_server;', $default);
        $default = str_replace('# include snippets/snakeoil.conf;', 'include snippets/snakeoil.conf;', $default);

        file_put_contents($default_path, $default);
    }

    /**
     * Create Let's Encrypt certificate and enable https in nginx host.
     *
     * @param  string  $domain
     * @return \Gogol\VpsManagerCLI\Helpers\Response
     */
    public function create(string $domain): Response
    {
        if (! isValidDomain($domain)) {
            return $this->response()->wrongDomainName();
        }

        // Check if certificate exists already
        if ($this->exists($domain)) {
            return $this->response()->error('Let\'s Encrypt certificate for this host already exists.');
        }

        $isSubdomain = (bool) $this->getSubdomain($domain);

        $hosts = $isSubdomain ? [$domain] : [$domain, 'www.'.$domain];

        // Run certbot
        $cmd = 'certbot certonly --nginx --agree-tos -n -m '.$this->config('ssl_email').' -d '.implode(' -d ', $hosts);

        exec($cmd, $output, $return_var);

        if ($return_var !== 0) {
            return $this->response()->error('<error>Certificate could not be installed. Please install it manually via:</error><comment>'."\n".$cmd.'</comment>');
        }

        // Get certificate directory name
        preg_match('/'.preg_quote($this->certPath().'/', '/').'(.*)\/fullchain\.pem/', implode("\n", $output), $matches);

        $cert_name = $matches[1] ?? $domain;

        // Get nginx host configuration
        $nginx_conf = file_get_contents($this->nginx()->getAvailablePath($domain));

        if (! $isSubdomain) {
            // Replace http redirect with https redirect, and also non-www to www in one redirect scope
            $nginx_conf = $this->replaceRedirectSection($domain, $nginx_conf);
            $nginx_conf = $this->replaceDefaultHost($domain, $cert_name, $nginx_conf);
        } else {
            // For subdomains add subdomain sections
            $nginx_conf = $this->addSubdomainRedirectSection($domain, $nginx_conf);
            $nginx_conf = $this->addSubdomainSSLSection($domain, $cert_name, $nginx_conf);
        }

        // Update host configuration, new sections get the monitor too
        file_put_contents($this->nginx()->getAvailablePath($domain), $this->nginx()->addMonitorIncludes($nginx_conf));

        $this->hosting()->rebootNginx();

        return $this->response()->success('Certificates for '.($isSubdomain ? 'subdomain' : 'domain').' '.$domain.' have been successfully installed!');
    }
}
